# Generated by Django 5.1.4 on 2024-12-23 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_userprofile_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='permissions',
            field=models.JSONField(default=dict),
        ),
    ]
