# Generated by Django 5.1.4 on 2024-12-25 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refreshtoken',
            name='expire_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
