# Generated by Django 5.1.4 on 2024-12-29 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_alter_refreshtoken_expire_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refreshtoken',
            name='access_key',
        ),
        migrations.AlterField(
            model_name='refreshtoken',
            name='refresh_key',
            field=models.TextField(null=True, unique=True),
        ),
    ]
